### ISSUE TITLE
Online mode

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/VIAaaS#1]
Idea: using a https connection for logging in, so we can just keep the code without PLAY state listening

**Comment by creeper123123321** [comment]
TODO: proxy Mojang API (use cors anywhere?)
Make compatible with 1.7 clients

**Comment by creeper123123321** [comment]
CORS idea: using bookmarks in Mojang's domain

**Comment by Heath123** [comment]
Can't it just have login via chat like Geyser?
