### ISSUE TITLE
Error when starting VIAaaS from the last commit

### ISSUE THREAD

**Issue by 4drian3d** [ViaVersion/VIAaaS#135]
When starting VIAaaS it gives the following error (possibly because ViaRewind needs to be updated to be compatible with ViaVersion 4.x)
`15:37:50 INFO [main] [ViaVersion] ViaVersion is disabling, if this is a reload and you experience issues consider rebooting.
15:37:50 ERROR [main] [STDERR] Exception in thread "main" java.lang.NoClassDefFoundError: us/myles/ViaVersion/api/protocol/ProtocolRegistry
15:37:50 ERROR [main] [STDERR]  at de.gerrygames.viarewind.api.ViaRewindPlatform.init(ViaRewindPlatform.java:21)
15:37:50 ERROR [main] [STDERR]  at com.viaversion.aas.VIAaaSKt.initVia(VIAaaS.kt:167)
15:37:50 ERROR [main] [STDERR]  at com.viaversion.aas.VIAaaSKt.main(VIAaaS.kt:108)
15:37:50 ERROR [main] [STDERR] Caused by: java.lang.ClassNotFoundException: us.myles.ViaVersion.api.protocol.ProtocolRegistry
15:37:50 ERROR [main] [STDERR]  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
15:37:50 ERROR [main] [STDERR]  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
15:37:50 ERROR [main] [STDERR]  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
15:37:50 ERROR [main] [STDERR]  ... 3 more`

**Comment by creeper123123321** [comment]
I triggered a rebuild for latest commit. it should work now

**Comment by 4drian3d** [comment]
Now works fine, thank you
