### ISSUE TITLE
cosmicpvp kick

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/VIAaaS#184]

**Comment by creeper123123321** [comment]
io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/33 (class_2670) was larger than I expected, found 21 bytes extra whilst reading packet 33

**Comment by creeper123123321** [comment]
https://github.com/ViaVersion/ViaFabric/issues/21

**Comment by RaphiMC** [comment]
I joined the server with my utility mod (which can skip invalid packets and print them into the console) and it seems like every packet is a keep alive packet
![grafik](https://user-images.githubusercontent.com/50594595/129636116-b9050d2b-b56f-44d1-8b95-817165a6f628.png)
I am gonna try to debug that a little bit more.

**Comment by RaphiMC** [comment]
Fixed it locally, the server sends a 0x46 compression packet (in play state) and Via doesn't handle it apparently

**Comment by creeper123123321** [comment]
Related to GoLilyPad

**Comment by creeper123123321** [comment]
fixed viaaas code + waiting viaversion pr be merged
