### ISSUE TITLE
ViaAprilFools

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/VIAaaS#193]

**Comment by Kichura** [comment]
:tiny_potato:

**Comment by RaphiMC** [comment]
The ViaAprilFools on GitHub is over 13 month old and probably wouldn't even run with the latest ViaVersion anymore. It is also missing 20w14infinite. Should I update it or do you have any other ideas how you would implement it?

**Comment by kennytv** [comment]
I forgot if this worked, but here's the mappings file for 20w14infinite https://github.com/kennytv/ViaVersion/commit/4c36f9429048345d6e5f238f9da271063bacb863

**Comment by RaphiMC** [comment]
Looks like it could work. Its the same as my mapping file except my one also has particle mappings. I don't know if they are needed or not

**Comment by HowardZHY** [comment]
don't forgot 15w14a
