### ISSUE TITLE
Add ability to specify one single server to proxy.

### ISSUE THREAD

**Issue by ayunami2000** [ViaVersion/VIAaaS#196]
I only want to use this to proxy one server. The server specified by the client is through bungeecord, so the hostname is wrong. So I need it to proxy one server only (no need for authentication in my case either). Is this possible to add in? (For now I will be building this by hand with the changes I need for my use case)

**Comment by ayunami2000** [comment]
ok from my nonexistent kotlin knowledge i put this together locally (theres also an extra line in the config handler file for it) I know it lacks checks like incase it isnt a valid ip:port buuuut it shhhouuuuuld do the trick
![image](https://user-images.githubusercontent.com/24785136/159101552-f29c814f-59af-4a48-bbc9-aa316ff7d987.png)

**Comment by ayunami2000** [comment]
ok im also going to make my build assume version incase it cant detect it

**Comment by creeper123123321** [comment]
it can be used on bungeecord now: #201
