### ISSUE TITLE
Feature to use TheAltening API instead of manually specifying accounts (could be enabled in the config)

### ISSUE THREAD

**Issue by ayunami2000** [ViaVersion/VIAaaS#198]
This would make it super easy to setup VIAaaS and then people would simply be able to connect and if they don't have the OpenAuthMod then they could connect anyways just to check out the server. Of course their account would change every time but it would be neat nonetheless. (Personally I am going for a sort of variant where you don't need the websocket at all to use this)

**Comment by kennytv** [comment]
No
