### ISSUE TITLE
No usage documentation

### ISSUE THREAD

**Issue by Matando** [ViaVersion/VIAaaS#2]
Currently the README.md doesn't list any information on how to test this out.

I've run ./gradlew and can create releases just fine.

However, when it comes to testing VIaaS currently when connecting it just floods open a bunch of UDP ports between the minecraft client and VIAaaS.

I'm aware this is probably incomplete, but I'm interested and code comments aren't helping much.

**Comment by creeper123123321** [comment]
Added

**Comment by Matando** [comment]
Thank you. I got it working now too(mostly). Just waiting on online mode support. I've tried hacking it in with no success, heh.
