### ISSUE TITLE
Extend token expire time.

### ISSUE THREAD

**Issue by wmantly** [ViaVersion/VIAaaS#212]
Thank you for making such a great project!

Recently, the server I play on upgraded to 1.19.2 and refuses to use another great project of yours, ViaBackwards. Because of this, my Minecraft bot(s) based on minelayer do not work. I have been using the public version of this project and set up a local install too.

The bot(s) are supposed to be logged on 24/7, but the constant asking to "allow auth impersonation" is a real pain. Is there a way in the local settings file to simply say always allow? In my case, the local VIAaaS is only accessible via LAN so there is little to no security risk.

I know you can Send access token, but that only works for day. Is there a way to extend this time?

**Comment by creeper123123321** [comment]
You can check OpenAuthMod plugin message
