### ISSUE TITLE
Error while connecting to 1.19.3 server from 1.19.2

### ISSUE THREAD

**Issue by JIBSIL** [ViaVersion/VIAaaS#223]
### `viaversion dump` Output

https://dump.viaversion.com/ae9d32435d3b85e27ff159c765c81160de3f274824958dbb2eff51e6e1474ed6

### Console Error

```
This is a client error.

IndexOutOfBoundsException: readerIndex(1963) + length(8) exceeds writerIndex(1963): Unpooled HeapByteBuf(rdix 1963, wdix 1963, cap 1963/1963)
```

### Bug Description

Connecting to a 1.19.3 server from a 1.19.2 client.

(minehut.com)

### Steps to Reproduce

1. Login to minehut.com with a 1.19.2 client and a 1.19.3 connecting version (the hub)
2. Get disconnected
3. Non specific error in the console of the server

### Expected Behavior

The client should not be disconnected

### Checklist

- [X] I have checked if this is specific to VIAaaS platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) and the issue still persists.

**Comment by creeper123123321** [comment]
can't reproduce using latest viaaas
