### ISSUE TITLE
can't get viaversion to run

### ISSUE THREAD

**Issue by grandpa1946** [ViaVersion/VIAaaS#233]
### `viaversion dump` Output

https://dump.viaversion.com/cantrunthis

### Console Error

```
https://paste.gg/p/anonymous/41139c3838f547d480d358f2e9f8ce96/files/0793cc2b7f834b4bb9aa5b79b9cdd063/raw
```

### Bug Description

viaversion searches com/viaversion/viaversion/api/type/types/minecraft/MetaTypeTemplate instead of com/viaversion/viaversion/api/type/types/metadata/MetaTypeTemplate
(i think)

### Steps to Reproduce

run the jar

### Expected Behavior

jar runs successfully

### Checklist

- [ ] I have checked if this is specific to VIAaaS platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) and the issue still persists.

**Comment by burakroket** [comment]
i had similiar issue. I found this build working for me:

https://github.com/ViaVersion/VIAaaS/actions/runs/6509934995

**Comment by grandpa1946** [comment]
> i had similiar issue. I found this build working for me:
> 
> [ViaVersion/VIAaaS/actions/runs/6509934995](https://github.com/ViaVersion/VIAaaS/actions/runs/6509934995)

thanks!

**Comment by grandpa1946** [comment]
this did not solve the problem tho @FlorianMichael

**Comment by FlorianMichael** [comment]
Try https://github.com/ViaVersion/VIAaaS/actions/runs/6826427596
