### ISSUE TITLE
i need an config option to change https port.

### ISSUE THREAD

**Issue by Outfit8TSB** [ViaVersion/VIAaaS#239]
### Problem Description

there is no way to change the https ports, it runs 25543 permanently.
however, in hosting providers, i can't select the port what i want.

### Solution Description

add a configuration option to use custom https ports.
`https-ports: 25543`

### Alternatives

Using Playit.gg or ngrok. however, both ngrok and playit.gg needs to turn on the computer 24/7, causing too much electricity taxes. this is why i had to use a hosting provider.

### Additional Info

this function must be added on viaaas.yml

**Comment by creeper123123321** [comment]
HTTPS port is configurable via command line 
https://ktor.io/docs/server-configuration-file.html#command-line

**Comment by Outfit8TSB** [comment]
i see the page after i typed my instance web address
![image](https://github.com/user-attachments/assets/b913b606-fcb3-4ec6-8731-0f9da98243cd)
but i cannot authenticate because it says `disconnected: 1006`.
