### ISSUE TITLE
online mode login via chat

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/VIAaaS#28]
I personally wouldn't trust it, but...
- [x] add multiversion packet decoding
- [ ] refactor connection to connect when frontend state is PLAY 
- [ ] basic PLAY packets (chat, join game, empty chunks...)
- [x] warn about remote login and mojang blocking accounts

- [ ] todo: what does happen if server responds with different UUID or username???

**Comment by DoctorMacc** [comment]
Something that needs to be kept in mind is that this may not be possible with MSA accounts (currently there is no way to submit a username and password without a browser). What is possible is having the user log in from a browser using a method similar to consoles:

 https://cdn.discordapp.com/attachments/613168850925649981/786624407199547432/maxresdefault.png

**Comment by creeper123123321** [comment]
Alternatives: #29

**Comment by creeper123123321** [comment]
#29
