### ISSUE TITLE
create a bundled CORS proxy for easier setup

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/VIAaaS#48]

**Comment by creeper123123321** [comment]
maybe https://crp123-cors.herokuapp.com/ just alleviates it

**Comment by JamesTheAwesomeDude** [comment]
> maybe https://crp123-cors.herokuapp.com/ just alleviates it

I think this could be re-opened: 

![403 Forbidden for crp123-cors.herokuapp.com](https://user-images.githubusercontent.com/2776014/108614570-48ab4b80-73c1-11eb-8244-4ba9996a75dc.png)

when changing it to a self-hosted, I get the following:

![200 OK for localhost:8080](https://user-images.githubusercontent.com/2776014/108614604-9758e580-73c1-11eb-92fe-f889482f6687.png)

**Comment by creeper123123321** [comment]
> when changing it to a self-hosted, I get the following:

it's whitelisted only for https://viaversion.github.io/VIAaaS/

**Comment by creeper123123321** [comment]
I'm now allowing all origins, with a filter for minecraft apis.
