### ISSUE TITLE
find a way to keep page running on mobile background

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/VIAaaS#69]
Maybe playing a empty audio in loop

**Comment by creeper123123321** [comment]
Service worker + notifications may work?

**Comment by JamesTheAwesomeDude** [comment]
The bigger issue is that (IME) Minecraft restarts whenever it's tabbed-out-of *or split/unsplit*, so I don't see this avenue (managing VIAaaS from the gaming device itself) as very promising, unless it were to become integrated with the game.

(What is the technical reason that the client's token can't just be forwarded as-is, anyway?)

**Comment by creeper123123321** [comment]
> (What is the technical reason that the client's token can't just be forwarded as-is, anyway?)
Security reasons, it's probably not a good idea to send the account tokens to the instance

**Comment by creeper123123321** [comment]
#84

**Comment by creeper123123321** [comment]
https://developers.google.com/web/updates/2018/07/page-lifecycle-api#faqs

**Comment by creeper123123321** [comment]
notifications in chrome seems to be working to me
