### ISSUE TITLE
[Request] default hostname/parameters

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [ViaVersion/VIAaaS#72]
I'd like to be able to set a "default" hostname and parameters, for clients that don't specify one.

For example, when trying to connect to my VIAaaS proxy through [Geyser](https://github.com/GeyserMC/Geyser), Minecraft Bedrock Edition balks with an `Invalid IP` error at the following:

![Screenshot of Minecraft Bedrock Edition server editor, showing "2b2t" in the Server Name field; "2b2t.org._usqueegily._of.viaaas.ishygddt.xyz" in the IP Address field; and "19132" in the Port field](https://user-images.githubusercontent.com/2776014/108611254-877dd900-73a2-11eb-97aa-3dae985d4fee.png)

(However, the same client is rejected for not specifying a hostname when it tries to connect with a simplified IP.)

Allowing to specify defaults for the hostname and frontend-onlineness would allow this use-case.

**Comment by creeper123123321** [comment]
It happens because geyser doesn't forward the virtual host which the bedrock edition connected to the geyser, and it's is sending the address of you specified in geyser config. You can kinda of use geyser connect to workaround it

**Comment by creeper123123321** [comment]
About the default hostname: it kinda of doesn't make sense as it's a proxy like onion.to

**Comment by JamesTheAwesomeDude** [comment]
Actually, nevermind — the main use-case of this is covered instead by coding the parameters in to the front proxy:

```yml
remote:
  address: 2b2t.org._v1_12_2.viaaas.localhost
```
